/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : PRNG
 #	author : miyako
 #	2017/04/27
 #
 # --------------------------------------------------------------------------------*/



// --- MT19937
void uniform_int_distribution(sLONG_PTR *pResult, PackagePtr pParams);
